name: Add new Pool to xSPO-Alliance

on:
  push:
    branch: feature/issue-tmplate-imprvs
  issues:
    types: [opened, reopened]

jobs:
  issue-to-json:
    name: Convert issue body to json
    #if: contains(github.event.issue.body, '>>pool_bech32_id<<')
    runs-on: ubuntu-latest
    outputs:
      payload-parsed: ${{ steps.payload.outputs.json_var }}
    steps:
      - name: Run parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: 27
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - name: Set Output
        id: payload
        run: echo json_var='${{ steps.parse.outputs.payload }}' >> $GITHUB_OUTPUT

  execute-pipe:
    name: Adding new Pool
    #if: contains(github.event.issue.body, '>>pool_bech32_id<<')
    runs-on: ubuntu-latest
    needs: issue-to-json
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        #### Important, in case main branch is protected (for direct commits) it has to checkout in a valid branch
        ### In this case, change below
        #with:
        #  ref: '<branch_name>'
     
      - name: 'Pool add'
        id: status
        continue-on-error: true
        env:
          pool_bech32_id: ${{ fromJson(needs.issue-to-json.outputs.payload-parsed)['pool_bech32_id'] }}
        run: |
          #./scripts/add-pool.sh
          echo "status_output=already" >> $GITHUB_OUTPUT

      - id: close-0
        name: 'Close issue'
        uses: peter-evans/close-issue@v2
        if: ${{contains(steps.status.outputs.status_output,'not_registered')}}
        with:
          issue-number: 29
          close-reason: not_planned
          comment: Pool not registered on Mainnet or Pool retired
          labels: |
            pool_not_added

      - id: close-1
        name: 'Close issue'
        uses: peter-evans/close-issue@v2
        if: ${{contains(steps.status.outputs.status_output,'too_big')}}
        with:
          issue-number: 29
          close-reason: not_planned
          comment: Pool live stake is greater than 1M Ada
          labels: |
            pool_not_added

      - id: close-2
        name: 'Close issue'
        uses: peter-evans/close-issue@v2
        if: ${{contains(steps.status.outputs.status_output,'already')}}
        with:
          issue-number: 29
          close-reason: not_planned
          comment: Pool is already added!
          labels: |
            pool_not_added

      - id: close-3
        name: 'Close issue'
        uses: peter-evans/close-issue@v2
        with:
          issue-number: 29
          comment: Pool added!
          labels: |
            pool_added
      